ensight.text.rgb(1,1,1)
ensight.text.new_text("Wind")
ensight.text.select_begin(0)
ensight.text.visible("OFF")
#ensight.text.location_x(0.9)
#ensight.text.location_y(0.9)

#
ensight.line.select_default()
ensight.line.label_text_id(0)
ensight.line.new_line()
ensight.line.arrowhead("on_second_end")
ensight.line.select_begin(0)
ensight.line.rgb(1,1,1)
ensight.line.width(3)
ensight.line.location_x_1(0.95)
ensight.line.location_y_1(0.9)
ensight.line.location_x_2(0.8)
ensight.line.location_y_2(0.9)

ensight.text.new_text("HP tip")
ensight.text.select_begin(1)
ensight.text.size(40)
ensight.text.visible("OFF")

ensight.line.select_default()
ensight.line.label_text_id(1)
ensight.line.new_line()
ensight.line.arrowhead("on_second_end")
ensight.line.select_begin(1)
ensight.line.rgb(1,1,1)
ensight.line.width(3)
ensight.line.location_x_1(0.975)
ensight.line.location_y_1(0.045)
ensight.line.location_x_2(0.885)
ensight.line.location_y_2(0.045)


ensight.view_transf.select_tool(0.524738669,0.732504904,0.0697127283,0.27657479)